language: python
python:
  - "2.7"
  - "3.6"
before_script:
  - pip install pytest
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=program_dir/ program_dir/test_1.py
after_success: coveralls
